name: base
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=py_0
  - anyio=3.5.0=py38h578d9bd_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h497a2fe_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotli-python=1.0.9=py38heb0550a_2
  - brotlipy=0.7.0=py38h497a2fe_1003
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38h3931269_0
  - cfitsio=4.0.0=h9a35b8e_0
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=2.0.11=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-completion=0.5.2=py38h578d9bd_3
  - click-log=0.3.2=pyh9f0ad1d_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h9ce1e76_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py38h497a2fe_1
  - dash=2.1.0=pyhd8ed1ab_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dask-core=2022.1.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py38h709712a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.16=py38h578d9bd_3
  - embree=2.17.7=ha770c72_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - flask=2.0.2=pyhd3eb1b0_0
  - flask-compress=1.10.1=pyhd3eb1b0_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - fonttools=4.29.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2022.1.0=pyhd8ed1ab_0
  - geos=3.10.2=h9c3ff4c_0
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.26=pyhd8ed1ab_0
  - greenlet=1.1.2=py38h709712a_1
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2021.11.20=py38h678ac2f_1
  - imageio=2.14.1=pyh239f2a4_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py38h578d9bd_0
  - importlib-resources=3.3.1=pyhd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.8.0=py38he5a9106_0
  - ipython=7.31.1=py38h578d9bd_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py38h578d9bd_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-book=0.12.1=pyhd8ed1ab_0
  - jupyter-cache=0.4.3=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.3=pyhd8ed1ab_0
  - jupyter-sphinx=0.3.2=pyhd8ed1ab_1
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h578d9bd_1
  - jupyter_server=1.13.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - jupytext=1.11.5=pyh6002c4b_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.2=py38h1fd1430_1
  - krb5=1.19.2=h48eae69_3
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.81.0=h494985f_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libgomp=11.2.0=h1d223b6_12
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=13_linux64_openblas
  - libnghttp2=1.46.0=ha19adfc_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - linkify-it-py=1.0.3=pyhd8ed1ab_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown-it-py=1.1.0=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_1
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdit-py-plugins=0.2.8=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - myst-nb=0.13.1=pyhd8ed1ab_0
  - myst-parser=0.15.2=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py38h578d9bd_0
  - nbdime=3.1.1=pyhd8ed1ab_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h9c3ff4c_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.22.2=py38h6ae9a64_0
  - numpy-stl=2.16.3=py38h6c62de6_2
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.0=py38h43a58ef_0
  - pandoc=2.17.1.1=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py38he2f12e7_0
  - pip=22.0.3=pyhd8ed1ab_0
  - plotly=5.5.0=py_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.1=py38h578d9bd_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydata-sphinx-theme=0.7.2=pyhd8ed1ab_0
  - pyembree=0.1.6=py38hcb8c335_1
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py38h497a2fe_0
  - pysocks=1.7.1=py38h578d9bd_4
  - python=3.8.12=h0744224_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-utils=3.1.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py38h6c62de6_1
  - pyyaml=6.0=py38h497a2fe_3
  - pyzmq=22.3.0=py38h2035c66_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - rtree=0.9.7=py38h02d302b_3
  - scikit-image=0.19.1=py38h43a58ef_0
  - scipy=1.8.0=py38h56a6a73_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.7.1=py38h578d9bd_0
  - shapely=1.8.0=py38h596eeab_5
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py38h578d9bd_2
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.4.0=pyh6c4a22f_1
  - sphinx-book-theme=0.1.10=pyhd8ed1ab_0
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.5.0=pyhd8ed1ab_0
  - sphinx-external-toc=0.2.3=pyhd8ed1ab_0
  - sphinx-jupyterbook-latex=0.4.6=pyhd8ed1ab_0
  - sphinx-multitoc-numbering=0.1.3=pyhd8ed1ab_0
  - sphinx-panels=0.6.0=pyhd8ed1ab_0
  - sphinx-thebe=0.0.10=pyhd8ed1ab_0
  - sphinx-togglebutton=0.2.3=pyhd3deb0d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=2.2.1=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_1
  - sqlalchemy=1.4.31=py38h497a2fe_0
  - sqlite=3.37.2=hc218d9a_0
  - tenacity=8.0.1=py38h06a4308_0
  - terminado=0.13.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tifffile=2022.2.2=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - unicodedata2=14.0.0=py38h497a2fe_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py38h578d9bd_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - autoprop==4.0.2
    - chardet==4.0.0
    - colorlog==6.6.0
    - commonmark==0.9.1
    - cython==0.29.27
    - glooey==0.3.6
    - lxml==4.7.1
    - mapbox-earcut==1.0.0
    - meshio==5.3.0
    - more-itertools==8.12.0
    - mpmath==1.2.1
    - msgpack==1.0.3
    - numexpr==2.8.1
    - opencv-contrib-python==4.5.5.62
    - opencv-python==4.5.5.62
    - psutil==5.9.0
    - pycollada==0.7.2
    - pyglet==1.5.21
    - python-fcl==0.6.1
    - rich==11.1.0
    - signature-dispatch==1.0.0
    - svg-path==4.1
    - sympy==1.9
    - tables==3.7.0
    - triangle==20220202
    - trimesh==3.9.43
    - typeguard==2.13.3
    - vecrec==0.3.1
    - xatlas==0.0.6
    - xxhash==2.0.2
